export class Partido {

    constructor(
        public cantidad,
        public ch_id,
        public mt_acumulado,
        public mt_date: string,
        public mt_goal1: number,
        public mt_goal2: number,
        public mt_id: number,
        public mt_idchampionship: number,
        public mt_idround: number,
        public mt_idteam1: number,
        public mt_idteam2: number,
        public mt_played: number,
        public rd_acumulado: number,
        public rd_id: number,
        public rd_idchampionship: number,
        public rd_round: number,
        public rs_date: string,
        public rs_id: number,
        public rs_idmatch: number,
        public rs_idpenca: number,
        public rs_iduser: number,
        public rs_points: number,
        public rs_res1: number,
        public rs_res2: number,
        public rs_result: number,
        public rs_round: string,
        public t1nome: string,
        public t2nome: string,
        public tm1_id: number,
        public tm1_logo: string,
        public tm2_id: number,
        public tm2_logo: string,
        public tm_grupo: string,
        public tm_id: number,
        public tm_idchampionship: number,
        public tm_logo: string,
        public tm_name: string,
        public tm_played: number,
        public tm_points: number,
        public disabled: string,
        public played: string,
        public acerto: string
      ) {  }
    
    }